### ISSUE TITLE
Optimize Firewalls

### ISSUE THREAD

**Issue by hmert** [okulbilisim/ojs#745]
app/config/security.yml
- [x] DOC
```
        api_doc:
            pattern: /api/doc
            stateless: true
            security: false
            anonymous: true
```
- [x] API Home
```
        api_home:
            pattern: /api/$
            stateless: true
            security: false
            anonymous: true
```
- [x] Analytics
```
        api_analytics:
            pattern: ^/api/analytics
            stateless: true
            security: false
            anonymous: true
```
- [x] public services
```
       api_public:
            pattern: ^/api/public/
            stateless: true
            security: false
            anonymous: true
```
- [x] mail template
```
       api_mail_template:
            pattern: ^/api/mail_template*
            stateless: true
            security: false
            anonymous: true
```
- [x] OAI
```
       api_oai:
            pattern: ^/api/oai
            stateless: true
            security: false
            anonymous: true
```
- [x] API
```
       api:
            pattern: ^/api/
            stateless: true
            security: true
            provider: user_db
            anonymous: true
            simple_preauth:
                authenticator: apikey_authenticator
```
- [x] Main
```
       main:
            switch_user: {parameter: _su}
            pattern: ^/
            anonymous: true
            provider: user_db
```
- [x] login
```
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path:            /user 
```
- [x] logout
```
        logout:
                path: /logout
                target: /
                success_handler: ojs.logout_listener
#                invalidate_session: false
#                delete_cookies:
#                    a: { path: null, domain: null }
#                    b: { path: null, domain: null }
#                handlers: [some.service.id, another.service.id]
#                success_handler: some.service.id
```
- [x] rememberme
```
       remember_me:
                key: df716bb554af3c6f04c34e0c6518253b
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
```
